"""empty message

Revision ID: b2fbba29a3d7
Revises: 8ef3b5b37e94
Create Date: 2017-10-14 17:36:07.048331

"""

# revision identifiers, used by Alembic.
revision = 'b2fbba29a3d7'
down_revision = '8ef3b5b37e94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
