"""empty message

Revision ID: e487fa33197e
Revises: ddfb1ae01248
Create Date: 2017-10-21 17:37:51.979480

"""

# revision identifiers, used by Alembic.
revision = 'e487fa33197e'
down_revision = 'ddfb1ae01248'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seismic_date', sa.DateTime(), nullable=True),
    sa.Column('richter_scale', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], [u'city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    op.drop_table('seism')
    # ### end Alembic commands ###
